/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminUserDisplay = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionId = IDL.Nat;
export const TransactionType = IDL.Variant({
  'mint' : IDL.Null,
  'transfer' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'admin' : IDL.Principal,
  'transactionType' : TransactionType,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const WalletBalance = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRegisteredUsersWithNames' : IDL.Func(
      [],
      [IDL.Vec(AdminUserDisplay)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTransactionHistory' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionLedger' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func(
      [IDL.Opt(IDL.Principal)],
      [WalletBalance],
      ['query'],
    ),
  'getWalletDetailsWithPrincipal' : IDL.Func(
      [IDL.Principal],
      [UserProfile],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminUserDisplay = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionId = IDL.Nat;
  const TransactionType = IDL.Variant({
    'mint' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'admin' : IDL.Principal,
    'transactionType' : TransactionType,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const WalletBalance = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRegisteredUsersWithNames' : IDL.Func(
        [],
        [IDL.Vec(AdminUserDisplay)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTransactionHistory' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionLedger' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func(
        [IDL.Opt(IDL.Principal)],
        [WalletBalance],
        ['query'],
      ),
    'getWalletDetailsWithPrincipal' : IDL.Func(
        [IDL.Principal],
        [UserProfile],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };